In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer


In [2]:
df = pd.read_excel('./dr.atashi.tasbihchi.xlsx')
df.head(10)
df.info()
df.tail()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5876 entries, 0 to 5875
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5876 non-null   int64  
 1   age                4879 non-null   float64
 2   age.diag           5781 non-null   float64
 3   age.menarch        5425 non-null   float64
 4   age.menop          4910 non-null   float64
 5   Occupation         300 non-null    float64
 6   education          5025 non-null   float64
 7   marital            5591 non-null   float64
 8   gravity            5379 non-null   float64
 9   lactaton           5230 non-null   float64
 10  first.pregnancy    5205 non-null   float64
 11  infertility        3988 non-null   float64
 12  reproduct          5189 non-null   float64
 13  mens               3918 non-null   float64
 14  ocp.use            4184 non-null   float64
 15  ocp                2874 non-null   float64
 16  HRT                3615 

id          age     age.diag  age.menarch    age.menop  \
count  5876.000000  4879.000000  5781.000000  5425.000000  4910.000000   
mean   3069.211538    48.443943    48.834112    13.049401    21.100611   
std    1806.643879    13.011699    61.993495     3.999003    24.051365   
min      63.000000     0.000000     0.000000     0.000000     0.000000   
25%    1531.750000    40.000000    40.000000    12.000000     0.000000   
50%    3000.500000    47.000000    47.000000    13.000000     0.000000   
75%    4470.250000    56.000000    55.000000    14.000000    48.000000   
max    7043.000000   446.000000  4614.000000   156.000000    65.000000   

       Occupation    education      marital      gravity     lactaton  ...  \
count  300.000000  5025.000000  5591.000000  5379.000000  5230.000000  ...   
mean     1.413333     2.212537     2.198176     1.044804    44.559881  ...   
std      0.705323     2.414914     2.001449     2.007711    41.483897  ...   
min      1.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%      1.000000     1.000000     2.000000     1.000000    15.000000  ...   
50%      1.000000     2.000000     2.000000     1.000000    36.000000  ...   
75%      2.000000     3.000000     2.000000     1.000000    60.000000  ...   
max      4.000000    57.000000    44.000000    96.000000   720.000000  ...   

       age.hysterectomy      smoking  personal.BC  personal.other.Ca  \
count       1524.000000  3852.000000  3740.000000        3706.000000   
mean           7.296588     0.351506     0.339840           0.019968   
std           16.897434     1.594432     0.473718           0.310205   
min            0.000000     0.000000     0.000000           0.000000   
25%            0.000000     0.000000     0.000000           0.000000   
50%            0.000000     0.000000     0.000000           0.000000   
75%            0.000000     0.000000     1.000000           0.000000   
max           82.000000    48.000000     1.000000          13.000000   

            F.H.BC   FH.other.Ca        weight       height         MTZ1  \
count  4042.000000   4150.000000   5277.000000  5120.000000  2333.000000   
mean      3.227610     38.290602     86.382597   158.055664     0.746249   
std     105.791955   1284.906858   1157.597067    38.993784     7.990340   
min       0.000000      0.000000      0.000000     0.000000     0.000000   
25%       0.000000      0.000000     62.000000   155.000000     0.000000   
50%       0.000000      0.000000     70.000000   159.000000     0.000000   
75%       0.000000      3.000000     78.000000   163.000000     0.000000   
max    6666.000000  66666.000000  84156.000000  1601.000000   234.000000   

            MTZ.2  
count  378.000000  
mean     8.092593  
std     26.923694  
min      1.000000  
25%      1.000000  
50%      3.000000  
75%      5.000000  
max    321.000000  

[8 rows x 28 columns]

In [3]:
df['age'].unique()

array([ 63.,  nan,  57.,  29.,  53.,  51.,  58.,  43.,  45.,  62.,  42.,
        44.,  79.,  48.,  47.,  40.,  39.,  69.,  64.,  55.,  46.,  54.,
        68.,  30.,  38.,  28.,  56.,  49.,  36.,  37.,  32.,  66.,  41.,
        31.,  52.,  50.,  33.,  60.,  27.,  61.,  35.,  26.,  59.,  65.,
        34.,  72.,  25.,  23.,  75.,  70.,  74.,  78.,  67.,  71.,  73.,
        77.,  87.,  76.,  83.,  81.,  18.,  82.,  80.,  24.,  84.,  85.,
         0.,  19.,  89.,  21.,   4.,  22.,  88.,  90., 446.])

In [4]:
df.isna().sum()

id                      0
age                   997
age.diag               95
age.menarch           451
age.menop             966
Occupation           5576
education             851
marital               285
gravity               497
lactaton              646
first.pregnancy       671
infertility          1888
reproduct             687
mens                 1958
ocp.use              1692
ocp                  3002
HRT                  2261
hystrectomy          2699
age.hysterectomy     4352
smoking              2024
personal.BC          2136
personal.other.Ca    2170
F.H.BC               1834
age.family           4008
FH.other.Ca          1726
weight                599
height                756
MTZ1                 3543
date.MTZ.1              0
MTZ.2                5498
MTZ.2.date              0
L.recurrence         5728
dtype: int64

In [5]:
#MTZ.2.data
np.random.seed(seed=0)
h = np.random.choice(a=df.index, replace=False, size=0)
df.loc[h, 'MTZ.2.date']

Series([], Name: MTZ.2.date, dtype: object)

In [6]:
#age
np.random.seed(seed=10)
a = np.random.choice(a=df.index, replace=False, size=997)
df.loc[a, 'age'] = np.nan

In [7]:
df.isna().sum()

id                      0
age                  1813
age.diag               95
age.menarch           451
age.menop             966
Occupation           5576
education             851
marital               285
gravity               497
lactaton              646
first.pregnancy       671
infertility          1888
reproduct             687
mens                 1958
ocp.use              1692
ocp                  3002
HRT                  2261
hystrectomy          2699
age.hysterectomy     4352
smoking              2024
personal.BC          2136
personal.other.Ca    2170
F.H.BC               1834
age.family           4008
FH.other.Ca          1726
weight                599
height                756
MTZ1                 3543
date.MTZ.1              0
MTZ.2                5498
MTZ.2.date              0
L.recurrence         5728
dtype: int64

In [8]:
x_train, x_test , y_train , y_test = train_test_split(df.drop("age.family", axis= 1), df["age.family"],
                                                      test_size=0.6, random_state=5)

In [9]:
knn = KNNImputer(n_neighbors=5 , add_indicator=True)

In [10]:
x_train.columns

Index(['id', 'age', 'age.diag', 'age.menarch', 'age.menop', 'Occupation',
       'education', 'marital', 'gravity', 'lactaton', 'first.pregnancy',
       'infertility', 'reproduct', 'mens', 'ocp.use', 'ocp', 'HRT',
       'hystrectomy', 'age.hysterectomy', 'smoking', 'personal.BC',
       'personal.other.Ca', 'F.H.BC', 'FH.other.Ca', 'weight', 'height',
       'MTZ1', 'date.MTZ.1', 'MTZ.2', 'MTZ.2.date', 'L.recurrence'],
      dtype='object')

In [11]:
num = [col for col in x_train.columns if x_train[col].dtype != 'O']

In [12]:
x_train[num].head()

id   age  age.diag  age.menarch  age.menop  Occupation  education  \
5553  6124  61.0      61.0         18.0       54.0         1.0        2.0   
1045  1108  49.0      49.0         14.0        0.0         NaN        2.0   
4027  4090  51.0      51.0         13.0        0.0         NaN        0.0   
759    822  38.0      38.0         12.0        0.0         NaN        4.0   
1569  1632   NaN      47.0         14.0        NaN         NaN        2.0   

      marital  gravity  lactaton  ...  age.hysterectomy  smoking  personal.BC  \
5553      2.0      1.0      48.0  ...               NaN      NaN          NaN   
1045      2.0      1.0      72.0  ...               NaN      0.0          0.0   
4027      2.0      1.0      48.0  ...               NaN      NaN          NaN   
759       2.0      1.0      24.0  ...               NaN      0.0          0.0   
1569      2.0      1.0     120.0  ...              45.0      0.0          0.0   

      personal.other.Ca  F.H.BC  FH.other.Ca  weight  height  MTZ1  MTZ.2  
5553                NaN     NaN          NaN    59.0   159.0   NaN    NaN  
1045                0.0     1.0          0.0    72.0   169.0   0.0    NaN  
4027                NaN     NaN          4.0    79.0   146.0   NaN    NaN  
759                 0.0     0.0          0.0    93.0   168.0   0.0    4.0  
1569                0.0     0.0          0.0    75.0   158.0   0.0    NaN  

[5 rows x 28 columns]

In [13]:
knn.fit(x_train[num])

KNNImputer(add_indicator=True)

In [14]:
knn.transform(x_train[num])

array([[6.124e+03, 6.100e+01, 6.100e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [1.108e+03, 4.900e+01, 4.900e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [4.090e+03, 5.100e+01, 5.100e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       ...,
       [4.142e+03, 5.180e+01, 5.300e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [2.317e+03, 4.920e+01, 5.400e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [2.978e+03, 2.500e+01, 2.500e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00]])

In [15]:
pd.DataFrame(knn.transform(x_train[num])).head()

0     1     2     3     4    5    6    7    8      9   ...   45   46  \
0  6124.0  61.0  61.0  18.0  54.0  1.0  2.0  2.0  1.0   48.0  ...  1.0  1.0   
1  1108.0  49.0  49.0  14.0   0.0  1.4  2.0  2.0  1.0   72.0  ...  1.0  0.0   
2  4090.0  51.0  51.0  13.0   0.0  1.0  0.0  2.0  1.0   48.0  ...  1.0  1.0   
3   822.0  38.0  38.0  12.0   0.0  1.4  4.0  2.0  1.0   24.0  ...  1.0  0.0   
4  1632.0  48.0  47.0  14.0  39.6  1.2  2.0  2.0  1.0  120.0  ...  0.0  0.0   

    47   48   49   50   51   52   53   54  
0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
2  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

[5 rows x 55 columns]

In [16]:
x_test[num].isna().sum()

id                      0
age                  1092
age.diag               51
age.menarch           273
age.menop             589
Occupation           3337
education             493
marital               172
gravity               306
lactaton              403
first.pregnancy       421
infertility          1146
reproduct             418
mens                 1163
ocp.use              1025
ocp                  1809
HRT                  1351
hystrectomy          1615
age.hysterectomy     2615
smoking              1209
personal.BC          1281
personal.other.Ca    1295
F.H.BC               1095
FH.other.Ca          1030
weight                344
height                435
MTZ1                 2103
MTZ.2                3300
dtype: int64

In [17]:
pd.DataFrame(knn.transform(x_test[num])).isna().sum().sum()

0

In [18]:
df.fillna(method='bfill', inplace=True)
df['age'][20:30]

C:\Users\IraniaN\AppData\Local\Temp\ipykernel_10748\3599045779.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)


20    45.0
21    69.0
22    69.0
23    53.0
24    62.0
25    64.0
26    42.0
27    42.0
28    43.0
29    43.0
Name: age, dtype: float64

In [19]:
x_test[num].isna().sum()

id                      0
age                  1092
age.diag               51
age.menarch           273
age.menop             589
Occupation           3337
education             493
marital               172
gravity               306
lactaton              403
first.pregnancy       421
infertility          1146
reproduct             418
mens                 1163
ocp.use              1025
ocp                  1809
HRT                  1351
hystrectomy          1615
age.hysterectomy     2615
smoking              1209
personal.BC          1281
personal.other.Ca    1295
F.H.BC               1095
FH.other.Ca          1030
weight                344
height                435
MTZ1                 2103
MTZ.2                3300
dtype: int64

In [20]:
from sklearn.experimental import enable_iterative_imputer 
from sklearn.impute import IterativeImputer
train_mice = x_train.copy(deep = True)
x_test = IterativeImputer()
train_mice['age'] = x_test.fit_transform(train_mice[['id']])

In [21]:
train_mice['age'].isnull().sum()

0

In [22]:
from sklearn.impute import SimpleImputer
missing_values = df.isnull().sum()
print(missing_values)

id                     0
age                    0
age.diag               0
age.menarch            0
age.menop              3
Occupation             0
education              0
marital                0
gravity                0
lactaton               0
first.pregnancy        0
infertility            1
reproduct              0
mens                   0
ocp.use                9
ocp                    9
HRT                   30
hystrectomy          142
age.hysterectomy     142
smoking               13
personal.BC          422
personal.other.Ca    443
F.H.BC                 3
age.family             3
FH.other.Ca            4
weight                 0
height                 0
MTZ1                   3
date.MTZ.1             0
MTZ.2                 32
MTZ.2.date             0
L.recurrence          27
dtype: int64


In [23]:
mumerical_data = df.select_dtypes(include=[np.number])

In [24]:
imputer = KNNImputer(n_neighbors=5)

In [25]:
imputer_data = imputer.fit_transform(mumerical_data)

In [26]:
mn = missing_values.fillna(method = 'ffill')
df2 = df.fillna(method='ffill')
#imputer_data.to_csv('output.csv' , index=False)
df2

C:\Users\IraniaN\AppData\Local\Temp\ipykernel_10748\1437400098.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  mn = missing_values.fillna(method = 'ffill')
C:\Users\IraniaN\AppData\Local\Temp\ipykernel_10748\1437400098.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2 = df.fillna(method='ffill')


id   age  age.diag  age.menarch  age.menop  Occupation  education  \
0       63  63.0      63.0         20.0       40.0         2.0        1.0   
1       64  57.0      57.0         13.0       52.0         2.0        1.0   
2       65  57.0      57.0         13.0       52.0         2.0        1.0   
3       66  29.0      28.0         15.0        0.0         2.0        1.0   
4       67  51.0      53.0         13.0       50.0         2.0        2.0   
...    ...   ...       ...          ...        ...         ...        ...   
5871  7033  43.0      43.0         12.0       54.0         1.0        4.0   
5872  7035  56.0      56.0         13.0       54.0         1.0        2.0   
5873  7037  39.0      39.0         12.0       54.0         1.0        4.0   
5874  7041  57.0      48.0         14.0       54.0         2.0        4.0   
5875  7043  57.0      57.0         12.0       54.0         1.0        2.0   

      marital  gravity  lactaton  ...  F.H.BC  age.family  FH.other.Ca  \
0         2.0      1.0      48.0  ...     0.0          42          0.0   
1         2.0      2.0      48.0  ...     0.0          42          0.0   
2         2.0      2.0      48.0  ...     0.0          42          0.0   
3         2.0      1.0      48.0  ...     0.0          42          0.0   
4         2.0      1.0      96.0  ...     3.0          42          0.0   
...       ...      ...       ...  ...     ...         ...          ...   
5871      2.0      0.0       0.0  ...     4.0          65          6.0   
5872      2.0      0.0       0.0  ...     4.0          65          6.0   
5873      2.0      1.0       2.0  ...     4.0          65          6.0   
5874      1.0      0.0       0.0  ...     4.0          65          6.0   
5875      2.0      0.0       0.0  ...     4.0          65          6.0   

      weight  height  MTZ1  date.MTZ.1  MTZ.2  MTZ.2.date  L.recurrence  
0       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
1       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
2       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
3       65.0   155.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
4       80.0   162.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
...      ...     ...   ...         ...    ...         ...           ...  
5871    77.0   160.0   0.0      #NULL!    5.0      #NULL!             1  
5872    75.0   156.0   0.0      #NULL!    5.0      #NULL!             1  
5873    62.0   170.0   0.0      #NULL!    5.0      #NULL!             1  
5874    94.0   162.0   0.0      #NULL!    5.0      #NULL!             1  
5875    56.0   156.0   0.0      #NULL!    5.0      #NULL!             1  

[5876 rows x 32 columns]

In [27]:
df.update(pd.DataFrame(imputer_data, columns=mumerical_data.columns))

In [28]:
print(mn)

id                     0
age                    0
age.diag               0
age.menarch            0
age.menop              3
Occupation             0
education              0
marital                0
gravity                0
lactaton               0
first.pregnancy        0
infertility            1
reproduct              0
mens                   0
ocp.use                9
ocp                    9
HRT                   30
hystrectomy          142
age.hysterectomy     142
smoking               13
personal.BC          422
personal.other.Ca    443
F.H.BC                 3
age.family             3
FH.other.Ca            4
weight                 0
height                 0
MTZ1                   3
date.MTZ.1             0
MTZ.2                 32
MTZ.2.date             0
L.recurrence          27
dtype: int64


In [29]:
print(imputer_data)

[[6.300e+01 6.300e+01 6.300e+01 ... 1.470e+02 0.000e+00 2.000e+00]
 [6.400e+01 5.700e+01 5.700e+01 ... 1.470e+02 0.000e+00 2.000e+00]
 [6.500e+01 5.700e+01 5.700e+01 ... 1.470e+02 0.000e+00 2.000e+00]
 ...
 [7.037e+03 3.900e+01 3.900e+01 ... 1.700e+02 1.200e+00 5.000e+00]
 [7.041e+03 5.700e+01 4.800e+01 ... 1.620e+02 1.200e+00 5.000e+00]
 [7.043e+03 5.700e+01 5.700e+01 ... 1.560e+02 1.200e+00 5.000e+00]]


In [30]:
df2.fillna(0)

id   age  age.diag  age.menarch  age.menop  Occupation  education  \
0       63  63.0      63.0         20.0       40.0         2.0        1.0   
1       64  57.0      57.0         13.0       52.0         2.0        1.0   
2       65  57.0      57.0         13.0       52.0         2.0        1.0   
3       66  29.0      28.0         15.0        0.0         2.0        1.0   
4       67  51.0      53.0         13.0       50.0         2.0        2.0   
...    ...   ...       ...          ...        ...         ...        ...   
5871  7033  43.0      43.0         12.0       54.0         1.0        4.0   
5872  7035  56.0      56.0         13.0       54.0         1.0        2.0   
5873  7037  39.0      39.0         12.0       54.0         1.0        4.0   
5874  7041  57.0      48.0         14.0       54.0         2.0        4.0   
5875  7043  57.0      57.0         12.0       54.0         1.0        2.0   

      marital  gravity  lactaton  ...  F.H.BC  age.family  FH.other.Ca  \
0         2.0      1.0      48.0  ...     0.0          42          0.0   
1         2.0      2.0      48.0  ...     0.0          42          0.0   
2         2.0      2.0      48.0  ...     0.0          42          0.0   
3         2.0      1.0      48.0  ...     0.0          42          0.0   
4         2.0      1.0      96.0  ...     3.0          42          0.0   
...       ...      ...       ...  ...     ...         ...          ...   
5871      2.0      0.0       0.0  ...     4.0          65          6.0   
5872      2.0      0.0       0.0  ...     4.0          65          6.0   
5873      2.0      1.0       2.0  ...     4.0          65          6.0   
5874      1.0      0.0       0.0  ...     4.0          65          6.0   
5875      2.0      0.0       0.0  ...     4.0          65          6.0   

      weight  height  MTZ1  date.MTZ.1  MTZ.2  MTZ.2.date  L.recurrence  
0       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
1       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
2       68.0   147.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
3       65.0   155.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
4       80.0   162.0   0.0      #NULL!    2.0      #NULL!      18.08.78  
...      ...     ...   ...         ...    ...         ...           ...  
5871    77.0   160.0   0.0      #NULL!    5.0      #NULL!             1  
5872    75.0   156.0   0.0      #NULL!    5.0      #NULL!             1  
5873    62.0   170.0   0.0      #NULL!    5.0      #NULL!             1  
5874    94.0   162.0   0.0      #NULL!    5.0      #NULL!             1  
5875    56.0   156.0   0.0      #NULL!    5.0      #NULL!             1  

[5876 rows x 32 columns]

In [31]:
df2.to_csv('output.csv' , index=False)